---
- name: Deploy XYZ AdminModule on Kubernetes
  hosts: docker_host
  gather_facts: no

  tasks:
    - name: Apply Deployment manifest
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/deployment.yaml"

    - name: Apply Service manifest
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/service.yaml"


