---
- name: Deploy XYZ AdminModule on Kubernetes
  hosts: docker_host
  gather_facts: no

  tasks:
    - name: Apply Deployment manifest
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('file', 'k8s/deployment.yaml') }}"

    - name: Apply Service manifest
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('file', 'k8s/service.yaml') }}"
